language: ruby
cache: bundler
rvm:
- 2.2.3
deploy:
  gem: 
    master: simple-https-client
  gemspec: shc.gemspec
  on:
    tags: true
    repo: sfeuga/simple-http_s-client
notifications:
  email:
    recipients:
      - sfeuga@member.fsf.org
    on_success: change
    on_failure: always
